server:
  servlet:
    context-path: /stu_managerv2
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: sun19950305
#    url: jdbc:mysql://47.106.69.227:3306/stu_managerV2?serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://47.106.69.227:3306/stu_managerV2?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/studentmanagerV2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    maxActive: 20
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: ["classpath:/static/"]
  thymeleaf:
    cache: false
  # 文件上传的大小和请求设置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  #重启热部署
devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 35729
  restart:
    enabled: true #是否支持热部署
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hmwl.pojo
logging:
  level:  {"com.hmwl":"trace"}
